Do not set GIT_TERMINAL_PROMPT=0
The comment explains that is was done because git prompts for password when cloning non-existent repo from GitHub.
However, I tried and was not able to reproduce the behavior - instead, cloning failed with the following message:
```
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

So, it seems that the workaround is no longer necessary and can be removed.

Fixes https://github.com/cesanta/mos-tool/issues/22

CL: mos: Do not set GIT_TERMINAL_PROMPT=0

PUBLISHED_FROM=29ea072009e87e86ef6a35562f574500960b6954