Make WebSocket error more readable, do not retry on bad code
Fixes https://github.com/cesanta/mos-tool/issues/29

Before:

```
E0121 11:52:00.295087    6136 reconnect_wrapper.go:93] [reconnectWrapperCodec to ws://192.168.1.242/rpc; connect in 2.00s] connection error: bad status
bad status
/build/mos-latest-T6VcsC/mos-latest-201901152258+a9afdd6~bionic0/obj-x86_64-linux-gnu/src/cesanta.com/common/go/mgrpc/mgrpc.go:152:
/build/mos-latest-T6VcsC/mos-latest-201901152258+a9afdd6~bionic0/obj-x86_64-linux-gnu/src/cesanta.com/common/go/mgrpc/mgrpc.go:181:
/build/mos-latest-T6VcsC/mos-latest-201901152258+a9afdd6~bionic0/obj-x86_64-linux-gnu/src/cesanta.com/common/go/mgrpc/mgrpc.go:228:
E0121 11:52:02.328816    6136 reconnect_wrapper.go:93] [reconnectWrapperCodec to ws://192.168.1.242/rpc; connect in 2.00s] connection error: bad status
bad status
/build/mos-latest-T6VcsC/mos-latest-201901152258+a9afdd6~bionic0/obj-x86_64-linux-gnu/src/cesanta.com/common/go/mgrpc/mgrpc.go:152:
/build/mos-latest-T6VcsC/mos-latest-201901152258+a9afdd6~bionic0/obj-x86_64-linux-gnu/src/cesanta.com/common/go/mgrpc/mgrpc.go:181:
/build/mos-latest-T6VcsC/mos-latest-201901152258+a9afdd6~bionic0/obj-x86_64-linux-gnu/src/cesanta.com/common/go/mgrpc/mgrpc.go:228:
E0121 11:52:04.470696    6136 reconnect_wrapper.go:93] [reconnectWrapperCodec to ws://192.168.1.242/rpc; connect in 2.00s] connection error: bad status
bad status
/build/mos-latest-T6VcsC/mos-latest-201901152258+a9afdd6~bionic0/obj-x86_64-linux-gnu/src/cesanta.com/common/go/mgrpc/mgrpc.go:152:
/build/mos-latest-T6VcsC/mos-latest-201901152258+a9afdd6~bionic0/obj-x86_64-linux-gnu/src/cesanta.com/common/go/mgrpc/mgrpc.go:181:
/build/mos-latest-T6VcsC/mos-latest-201901152258+a9afdd6~bionic0/obj-x86_64-linux-gnu/src/cesanta.com/common/go/mgrpc/mgrpc.go:228:
^C
```

After:
```
E0121 11:52:16.750905    6162 reconnect_wrapper.go:99] [reconnectWrapperCodec to ws://192.168.1.242/rpc; connect in 2.00s] fatal connection error: WebSocket connection failed: Invalid HTTP response code returned. Missing rpc-ws library?: bad status
bad status
/home/rojer/go/src/cesanta.com/common/go/mgrpc/mgrpc.go:154: Invalid HTTP response code returned. Missing rpc-ws library?
/home/rojer/go/src/cesanta.com/common/go/mgrpc/mgrpc.go:185: WebSocket connection failed
/home/rojer/go/src/cesanta.com/common/go/mgrpc/mgrpc.go:232:
Error: bad status
/home/rojer/go/src/cesanta.com/common/go/mgrpc/mgrpc.go:154: Invalid HTTP response code returned. Missing rpc-ws library?
/home/rojer/go/src/cesanta.com/common/go/mgrpc/mgrpc.go:185: WebSocket connection failed
/home/rojer/go/src/cesanta.com/common/go/mgrpc/mgrpc.go:232:
/home/rojer/go/src/cesanta.com/common/go/mgrpc/codec/reconnect_wrapper.go:100:
/home/rojer/go/src/cesanta.com/common/go/mgrpc/codec/reconnect_wrapper.go:127: fatal connection error, not reconnecting
/home/rojer/go/src/cesanta.com/common/go/mgrpc/codec/reconnect_wrapper.go:168:
/home/rojer/go/src/cesanta.com/common/go/mgrpc/mgrpc.go:379:
/home/rojer/go/src/cesanta.com/mos/dev/dev_conn.go:229:
/home/rojer/go/src/cesanta.com/mos/main.go:176: call failed
```

CL: Make WebSocket error more readable, do not retry on bad code

PUBLISHED_FROM=17d2b651a447842ad26b538cc076e68d017b6801